version: "3.9"
services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh /app/entrypoint.dev.sh"
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ..:/app/
      - media_volume:/app/media
      - static_volume:/app/staticfiles

    networks:
      - hrresumebank-network

networks:
  hrresumebank-network:
    external: true

volumes:
  media_volume:
  static_volume:
  postgres_data: