services:
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ../.env
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - hrresumebank-network
