version: "3.9"
services:
  postgres2:
    image: postgres:15
    container_name: example-db2
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data/
    env_file:
      - ../.env
    networks:
      - hrresumebank-network
