FROM python:3.12-slim

# Не создает *.pyc файлы
ENV PYTHONDONTWRITEBYTECODE 1
# Не создает буфиризацию, логи показываются сразу
ENV PYTHONUNBUFFERED 1


WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-dev \
    libpq-dev \
    netcat-openbsd \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Создаем пользователя для запуска приложения
RUN adduser --disabled-password --gecos '' app

RUN pip install --no-cache-dir uv

COPY requirements.txt .
RUN uv pip install --no-cache --system -r requirements.txt && \
    uv pip install --no-cache --system gunicorn

COPY --chown=app:app . /app/
COPY --chown=app:app entrypoint/entrypoint.prod.sh /app/entrypoint/entrypoint.prod.sh

RUN chmod +x /app/entrypoint/entrypoint.prod.sh

USER app

ENTRYPOINT ["/app/entrypoint/entrypoint.prod.sh"]
