# Generated by Django 5.2.5 on 2025-10-24 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('audit', '0001_initial'), ('audit', '0002_delete_activitylog')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
