# Generated by Django 5.2.5 on 2025-10-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_delete_activitylog'),
    ]

    operations = [
    ]
