# Generated by Django 5.2.5 on 2025-10-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_auditlog'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS auditlog_logentry;"),
    ]
