# Generated by Django 5.2.5 on 2025-10-24 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('help', '0001_initial'), ('help', '0002_remove_helparticle_help_articl_is_feat_fb8dfc_idx_and_more'), ('help', '0003_delete_helpmedia')]

    dependencies = [
        ('resumes', '0017_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='help.helpcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория справки',
                'verbose_name_plural': 'Категории справки',
                'db_table': 'help_category',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('tags', models.CharField(blank=True, help_text='Разделяйте теги запятыми', max_length=500, verbose_name='Теги')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Популярная статья')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('related_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.template', verbose_name='Связанный шаблон')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help.helpcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья справки',
                'verbose_name_plural': 'Статьи справки',
                'db_table': 'help_article',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='help.helpcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'db_table': 'help_faq',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='HelpMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='help_system/images/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='help.helparticle', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Медиафайл справки',
                'verbose_name_plural': 'Медиафайлы справки',
                'db_table': 'help_media',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='helparticle',
            index=models.Index(fields=['is_published', 'category'], name='help_articl_is_publ_cb61d0_idx'),
        ),
        migrations.RemoveField(
            model_name='helparticle',
            name='is_featured',
        ),
        migrations.DeleteModel(
            name='HelpMedia',
        ),
    ]
