# Generated by Django 5.2.5 on 2025-10-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='helparticle',
            name='help_articl_is_feat_fb8dfc_idx',
        ),
        migrations.RemoveField(
            model_name='helparticle',
            name='is_featured',
        ),
    ]
