# Generated by Django 5.2.5 on 2025-10-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_remove_helparticle_help_articl_is_feat_fb8dfc_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpMedia',
        ),
    ]
