# Generated by Django 5.2.5 on 2025-11-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial_squashed_0003_delete_helpmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helparticle',
            name='related_template',
        ),
    ]
