# Generated by Django 5.2.5 on 2025-08-29 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите действия', max_length=100, verbose_name='Названия действия')),
                ('code', models.CharField(help_text='Введите код разрешения', unique=True, verbose_name='Уникальный код разрешения')),
                ('description', models.TextField(help_text='Ввидите описание', verbose_name='Описание назначения решения')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешении',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название роли', max_length=50, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, help_text='Введите описание роли', verbose_name='Описание роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название группы', max_length=150, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, help_text='Введите описание группы', verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите подразделение', max_length=150, unique=True, verbose_name='Название подразделения')),
                ('description', models.TextField(blank=True, help_text='Введите описание', verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, help_text='Выберите подразделение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resumes.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Поздразделение',
                'verbose_name_plural': 'Подразделение',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(help_text='Выберите разрешение', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='resumes.permission', verbose_name='Разрешение')),
                ('role', models.ForeignKey(help_text='Выберите роль', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permission', to='resumes.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль/Разрешение',
                'verbose_name_plural': 'Роли/Разрешении',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(help_text='Выберите подразделение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='resumes.department', verbose_name='Департамент/Отдел')),
                ('user', models.OneToOneField(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(help_text='Выберите подразделение', on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='resumes.department', verbose_name='Принадлежность группы к подразделению')),
                ('group', models.ForeignKey(help_text='Выберите группу', on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='resumes.team', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Департамент/Группа',
                'verbose_name_plural': 'Департаменты/Группы',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, help_text='Выберите подразделение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='resumes.department', verbose_name='Ограничение роли в рамка подразделения')),
                ('role', models.ForeignKey(help_text='Выберите роль', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='resumes.role', verbose_name='Назначенная роль')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь/Роль',
                'verbose_name_plural': 'Пользователи/Роли',
            },
        ),
    ]
