# Generated by Django 5.2.5 on 2025-09-06 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Тип действия')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Дополнительные детали')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил действие')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Жарнал действий',
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название шаблона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал шаблон')),
            ],
            options={
                'verbose_name': 'Шаблон резюме/карточка',
                'verbose_name_plural': 'Шаблоны резюме/карточки',
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('main_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_template', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал запись')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_template', to='resumes.template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Запись резюме/Сущность',
                'verbose_name_plural': 'Записи резюме/Сущности',
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя поля')),
                ('type_field', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Булево'), ('email', 'Почта'), ('image', 'Изображение'), ('file', 'Файл')], max_length=50, verbose_name='Тип данных')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательность заполнения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_primary', models.BooleanField(default=False, help_text="Если отмечено — это поле используется как 'главное'             для отображения Entity (например ФИО или Название компании).")),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_templatefield', to='resumes.template', verbose_name='Шаблон, которому принадлежит поле')),
            ],
            options={
                'verbose_name': 'Полe шаблона',
                'verbose_name_plural': 'Поля шаблона',
                'db_table': 'template_field',
            },
        ),
        migrations.CreateModel(
            name='EntityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Значение текстового поля')),
                ('value_number', models.IntegerField(blank=True, null=True, verbose_name='Числовое значение')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('value_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('value_images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Булево значение')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_entitydate', to='resumes.entity', verbose_name='К какой сущности относится значение')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_entitydate', to='resumes.templatefield', verbose_name='К какому полю относится значение')),
            ],
            options={
                'verbose_name': 'Значения динамического поля',
                'verbose_name_plural': 'Значения динамических полей',
                'db_table': 'entity_data',
                'indexes': [models.Index(fields=['value_text', 'value_number', 'value_date'], name='entity_data_value_t_eb0eac_idx')],
            },
        ),
    ]
