# Generated by Django 5.2.5 on 2025-10-24 09:05

import core.apps.resumes.models.file_storage
import core.apps.resumes.models.profile_image
import django.contrib.postgres.indexes
import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('resumes', '0001_initial'), ('resumes', '0002_remove_entitydata_entity_remove_entitydata_field_and_more'), ('resumes', '0003_card'), ('resumes', '0004_remove_template_created'), ('resumes', '0005_rename_type_field_templatefield_field_type_and_more'), ('resumes', '0006_templatefield_is_primary_alter_card_values'), ('resumes', '0007_card_main_name'), ('resumes', '0008_templatefield_is_visible'), ('resumes', '0009_templatefield_order'), ('resumes', '0010_alter_templatefield_options'), ('resumes', '0011_alter_card_options'), ('resumes', '0012_filestorage'), ('resumes', '0013_alter_filestorage_uploaded_file_profileimage'), ('resumes', '0014_alter_template_options_alter_card_created'), ('resumes', '0015_alter_card_options'), ('resumes', '0016_alter_card_values'), ('resumes', '0017_delete_log')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название шаблона')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Булево'), ('email', 'Почта'), ('choice', 'Выбор'), ('image', 'Изображение'), ('file', 'Файл')], max_length=50, verbose_name='Тип данных')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательность заполнения')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='resumes.template', verbose_name='Шаблон, которому принадлежит поле')),
                ('choices', models.TextField(blank=True, help_text='Введите значения, разделеными запятыми', verbose_name='Поле выбора')),
                ('is_primary', models.BooleanField(default=False, help_text="Если отмечено — это поле используется как 'главное'             для отображения в загаловке карточки (например ФИО или Название компании).")),
                ('is_visible', models.BooleanField(default=False, help_text='Если отмечено — это поле будет видно             в карточке резюме на главном экране')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок отображения в карточке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Полe шаблона',
                'verbose_name_plural': 'Поля шаблона',
                'db_table': 'template_field',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('values', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Значения полей')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_template', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал запись')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='resumes.template', verbose_name='Шаблон')),
                ('main_name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Наименование карточки')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'db_table': 'card',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['values'], name='card_values_531476_gin')],
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uploaded_file', models.FileField(upload_to=core.apps.resumes.models.file_storage._get_uploaded_file_name, verbose_name='Путь к файлу')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='resumes.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'file_storage',
                'ordering': ['create_at'],
                'indexes': [models.Index(fields=['card', 'create_at'], name='file_storag_card_id_b052e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to=core.apps.resumes.models.profile_image._get_uploaded_file_name, verbose_name='Изображение')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='resumes.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Изображение профиля',
                'verbose_name_plural': 'Изображения профиля',
                'db_table': 'profile_image',
                'ordering': ['create_at'],
                'indexes': [models.Index(fields=['card', 'create_at'], name='profile_ima_card_id_7e6ca1_idx')],
            },
        ),
    ]
