# Generated by Django 5.2.5 on 2025-08-28 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите подразделение', max_length=150, verbose_name='Название подразделения')),
                ('description', models.TextField(blank=True, help_text='Введите описание', verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, help_text='Выберите подразделение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resumes.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Поздразделение',
                'verbose_name_plural': 'Подразделение',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(help_text='Выберите подразделение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='resumes.department', verbose_name='Депортамент/Отдел')),
                ('user', models.OneToOneField(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Персонал',
            },
        ),
    ]
