# Generated by Django 5.2.5 on 2025-09-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitydata',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entitydata',
            name='field',
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='order',
        ),
        migrations.AddField(
            model_name='templatefield',
            name='choices',
            field=models.TextField(blank=True, help_text='Введите значения, разделеными запятыми', verbose_name='Поле выбора'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='type_field',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Булево'), ('email', 'Почта'), ('choice', 'Выбор'), ('image', 'Изображение'), ('file', 'Файл')], max_length=50, verbose_name='Тип данных'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='EntityData',
        ),
    ]
