# Generated by Django 5.2.5 on 2025-08-29 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Пользователь/Группа',
                'verbose_name_plural': 'Пользователи/Группы',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='resumes_use_user_id_72c711_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('user', 'role', 'department'), name='unique_user_role_department'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('user', 'role', 'department'), name='unique_user_role_with_department'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(help_text='Выберите группу', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='resumes.team', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
