# Generated by Django 5.2.5 on 2025-09-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='main_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Если отмечено — это поле используется как 'главное' для отображения Entity (например ФИО или Название компании)."),
        ),
    ]
