# Generated by Django 5.2.5 on 2025-09-14 07:24

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_entitydata_entity_remove_entitydata_field_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('values', models.JSONField(default=dict)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_template', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал запись')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='resumes.template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'db_table': 'card',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['values'], name='card_values_531476_gin')],
            },
        ),
    ]
