# Generated by Django 5.2.5 on 2025-08-29 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_usergroup_alter_department_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='departmentgroup',
            constraint=models.UniqueConstraint(fields=('group', 'department'), name='unique_group_department'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group'),
        ),
    ]
