# Generated by Django 5.2.5 on 2025-08-29 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_departmentgroup_unique_group_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_user_role_department',
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_user_role_with_department',
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('user', 'role'), name='unique_user_role_department'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('user', 'role'), name='unique_user_role_with_department'),
        ),
    ]
