# Generated by Django 5.2.5 on 2025-09-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='created',
        ),
    ]
