# Generated by Django 5.2.5 on 2025-08-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_userrole_unique_user_role_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(help_text='Введите название группы', max_length=150, unique=True, verbose_name='Название группы'),
        ),
    ]
