# Generated by Django 5.2.5 on 2025-09-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_template_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatefield',
            old_name='type_field',
            new_name='field_type',
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='resumes.template', verbose_name='Шаблон, которому принадлежит поле'),
        ),
    ]
