# Generated by Django 5.2.5 on 2025-09-02 08:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_alter_team_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_lower_title_role'),
        ),
    ]
