# Generated by Django 5.2.5 on 2025-09-14 18:56

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_rename_type_field_templatefield_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Если отмечено — это поле используется как 'главное'             для отображения в загаловке карточки (например ФИО или Название компании)."),
        ),
        migrations.AlterField(
            model_name='card',
            name='values',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
