# Generated by Django 5.2.5 on 2025-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_templatefield_is_primary_alter_card_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='main_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Наименование карточки'),
        ),
    ]
