# Generated by Django 5.2.5 on 2025-09-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_card_main_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Если отмечено — это поле будет видно             в карточке резюме на главном экране'),
        ),
    ]
