# Generated by Django 5.2.5 on 2025-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_templatefield_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Порядок отображения в карточке', verbose_name='Порядок'),
        ),
    ]
