# Generated by Django 5.2.5 on 2025-09-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_templatefield_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatefield',
            options={'ordering': ['order'], 'verbose_name': 'Полe шаблона', 'verbose_name_plural': 'Поля шаблона'},
        ),
    ]
