# Generated by Django 5.2.5 on 2025-09-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_alter_templatefield_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['create_at'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
    ]
