# Generated by Django 5.2.5 on 2025-09-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_alter_card_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uploaded_file', models.FileField(upload_to='FileStorage._get_uploaded_file_name', verbose_name='Путь к файлу')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='resumes.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'file_storage',
                'ordering': ['create_at'],
                'indexes': [models.Index(fields=['card', 'create_at'], name='file_storag_card_id_b052e7_idx')],
            },
        ),
    ]
