# Generated by Django 5.2.5 on 2025-09-25 13:48

import core.apps.resumes.models.file_storage
import core.apps.resumes.models.profile_image
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_filestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='uploaded_file',
            field=models.FileField(upload_to=core.apps.resumes.models.file_storage._get_uploaded_file_name, verbose_name='Путь к файлу'),
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to=core.apps.resumes.models.profile_image._get_uploaded_file_name, verbose_name='Изображение')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='resumes.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Изображение профиля',
                'verbose_name_plural': 'Изображения профиля',
                'db_table': 'profile_image',
                'ordering': ['create_at'],
                'indexes': [models.Index(fields=['card', 'create_at'], name='profile_ima_card_id_7e6ca1_idx')],
            },
        ),
    ]
