# Generated by Django 5.2.5 on 2025-10-02 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_alter_filestorage_uploaded_file_profileimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_template', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал запись'),
        ),
    ]
