# Generated by Django 5.2.5 on 2025-10-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_alter_template_options_alter_card_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-create_at'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
    ]
