# Generated by Django 5.2.5 on 2025-10-13 18:40

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0015_alter_card_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='values',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Значения полей'),
        ),
    ]
