# Generated by Django 5.2.5 on 2025-10-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0016_alter_card_values'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
