# Generated by Django 5.2.5 on 2025-11-09 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial_squashed_0017_delete_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_card', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал запись'),
        ),
    ]
